server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
        server-addr: 192.168.206.128:8848
    gateway:
      routes:
        - id: item   # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates:
            - Path=/items/**,/search/**  #每个微服务中controller里请求的通用路径，用 , 来分隔每个controller类
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**,/address/**
        - id: trade
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
hm:
  jwt:
    #签名秘钥，并把他放在hmall.jks里面
    location: classpath:hmall.jks #l路径
    alias: hmall #别名
    password: hmall123 #密码
    tokenTTL: 30m #时间
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi